import { Router } from "express";
import { z } from "zod";
import type { DatabasePool } from "../database/pool.js";
import { requireUser } from "../auth/middleware.js";
import type { AppConfig } from "../config.js";
import { uploadCertificate } from "../google/archive.js";
import { awardReward } from "./rewards.js";

async function recalculate(pool:DatabasePool,enrollmentId:string,config?:AppConfig){
  const stats=await pool.query(`SELECT COUNT(l.id)::int total,COUNT(lp.id) FILTER(WHERE lp.completed)::int completed FROM enrollments e JOIN lessons l ON l.course_id=e.course_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.enrollment_id=e.id WHERE e.id=$1 GROUP BY e.id`,[enrollmentId]);
  const total=stats.rows[0]?.total||0,completed=stats.rows[0]?.completed||0,progress=total?Math.round(100*completed/total):0;
  const questions=await pool.query(`SELECT COUNT(q.id)::int total,COUNT(DISTINCT qa.question_id) FILTER(WHERE qa.correct)::int completed FROM enrollments e JOIN lessons l ON l.course_id=e.course_id LEFT JOIN quiz_questions q ON q.lesson_id=l.id LEFT JOIN quiz_attempts qa ON qa.question_id=q.id AND qa.enrollment_id=e.id WHERE e.id=$1 GROUP BY e.id`,[enrollmentId]);
  const completion=await pool.query(`SELECT c.survey_enabled AS "surveyEnabled",EXISTS(SELECT 1 FROM reward_transactions rt WHERE rt.enrollment_id=e.id AND rt.activity_type='SURVEY_SUBMIT') AS "surveySubmitted" FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.id=$1`,[enrollmentId]);
  const quizDone=(questions.rows[0]?.total||0)===(questions.rows[0]?.completed||0),surveyDone=!completion.rows[0]?.surveyEnabled||completion.rows[0]?.surveySubmitted,done=total>0&&progress===100&&quizDone&&surveyDone;
  const enrollment=await pool.query(`UPDATE enrollments SET progress=$2,status=CASE WHEN $3 THEN 'COMPLETED' WHEN $2>0 THEN 'IN_PROGRESS' ELSE status END,completed_at=CASE WHEN $3 THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE id=$1 RETURNING user_id AS "userId"`,[enrollmentId,progress,done]);
  if(done&&enrollment.rows[0])await awardReward(pool,{userId:enrollment.rows[0].userId,enrollmentId,activityType:"COURSE_COMPLETE",sourceKey:`course:${enrollmentId}`,description:"과정 수료"});
  if(done){const certificateNumber=`SPARKPLUS-${new Date().getFullYear()}-${enrollmentId.slice(0,8).toUpperCase()}`;const inserted=await pool.query(`INSERT INTO certificates(enrollment_id,certificate_number) VALUES($1,$2) ON CONFLICT(enrollment_id) DO NOTHING RETURNING id`,[enrollmentId,certificateNumber]);if(inserted.rowCount&&config){const details=await pool.query(`SELECT u.name,u.email,c.title,cert.issued_at AS "issuedAt" FROM certificates cert JOIN enrollments e ON e.id=cert.enrollment_id JOIN users u ON u.id=e.user_id JOIN courses c ON c.id=e.course_id WHERE e.id=$1`,[enrollmentId]);uploadCertificate(config,{certificateNumber,...details.rows[0],issuedAt:new Date(details.rows[0].issuedAt).toISOString()}).then((driveFileId)=>driveFileId ? pool.query(`UPDATE certificates SET drive_file_id=$2 WHERE enrollment_id=$1`,[enrollmentId,driveFileId]) : null).catch(()=>undefined);}}return{progress,completed:done,surveySubmitted:Boolean(completion.rows[0]?.surveySubmitted)};
}
export function createLearningRouter(pool:DatabasePool,config?:AppConfig){const router=Router();router.use(requireUser(pool));
 router.get("/featured-tags",async(_req,res,next)=>{try{const result=await pool.query(`SELECT featured.tag FROM featured_course_tags featured WHERE featured.enabled=true AND EXISTS(SELECT 1 FROM course_tags tags JOIN courses c ON c.id=tags.course_id WHERE tags.tag=featured.tag AND c.status='OPEN' AND c.deleted_at IS NULL) ORDER BY featured.display_order,featured.tag`);res.json({data:result.rows.map((row)=>row.tag),error:null});}catch(e){next(e);}});
 router.get("/home",async(req,res,next)=>{try{const userId=req.currentUser!.id;const [stats,ranking,popular,badges]=await Promise.all([
   pool.query(`SELECT COUNT(*) FILTER(WHERE status IN ('ENROLLED','IN_PROGRESS'))::int AS "inProgress",COUNT(*) FILTER(WHERE status='COMPLETED')::int AS completed FROM enrollments WHERE user_id=$1 AND status<>'CANCELLED'`,[userId]),
   pool.query(`WITH monthly AS (SELECT u.id,u.name,COALESCE(o.name,'소속 미지정') dept,SUM(rt.points)::int points FROM users u JOIN reward_transactions rt ON rt.user_id=u.id AND date_trunc('month',rt.created_at)=date_trunc('month',now()) LEFT JOIN organizations o ON o.id=u.organization_id WHERE u.status='ACTIVE' GROUP BY u.id,o.name), ranked AS (SELECT *,ROW_NUMBER() OVER(ORDER BY points DESC,name)::int rank FROM monthly) SELECT rank,name,dept,points AS score,(id=$1) AS "isMe" FROM ranked ORDER BY rank LIMIT 3`,[userId]),
   pool.query(`SELECT c.id,c.title,c.category,c.level,c.thumbnail,COUNT(e.id)::int AS learners FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.status<>'CANCELLED' WHERE c.status='OPEN' AND c.deleted_at IS NULL GROUP BY c.id ORDER BY COUNT(e.id) DESC,c.created_at DESC LIMIT 3`),
   pool.query(`SELECT br.name,br.badge_type AS type,br.tone,ub.awarded_at AS "awardedAt" FROM user_badges ub JOIN badge_rules br ON br.id=ub.badge_rule_id WHERE ub.user_id=$1 ORDER BY ub.awarded_at DESC LIMIT 3`,[userId]),
 ]);const meRank=await pool.query(`WITH monthly AS (SELECT u.id,SUM(rt.points)::int points FROM users u JOIN reward_transactions rt ON rt.user_id=u.id AND date_trunc('month',rt.created_at)=date_trunc('month',now()) WHERE u.status='ACTIVE' GROUP BY u.id), ranked AS (SELECT id,ROW_NUMBER() OVER(ORDER BY points DESC,id)::int rank FROM monthly) SELECT rank FROM ranked WHERE id=$1`,[userId]);res.json({data:{stats:{...stats.rows[0],rank:meRank.rows[0]?.rank||null},ranking:ranking.rows,popular:popular.rows,badges:badges.rows},error:null});}catch(e){next(e);}});
 router.get("/courses",async(req,res,next)=>{try{const result=await pool.query(`SELECT c.id,c.title,c.category,c.level,c.status,c.description,c.thumbnail,c.start_date AS "startDate",c.end_date AS "endDate",c.survey_enabled AS "surveyEnabled",c.google_form_url AS "googleFormUrl",COALESCE((SELECT json_agg(ct.tag ORDER BY ct.tag) FROM course_tags ct WHERE ct.course_id=c.id),'[]') tags,e.id AS "enrollmentId",e.required,e.due_date AS "dueDate",e.status AS "enrollmentStatus",e.progress,e.completed_at AS "completedAt",cert.certificate_number AS "certificateNumber" FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.user_id=$1 LEFT JOIN certificates cert ON cert.enrollment_id=e.id WHERE c.deleted_at IS NULL AND c.status='OPEN' ORDER BY e.required DESC NULLS LAST,c.created_at DESC`,[req.currentUser!.id]);res.json({data:result.rows,error:null});}catch(e){next(e);}});
 router.get("/courses/:id",async(req,res,next)=>{try{const course=await pool.query(`SELECT c.id,c.title,c.category,c.level,c.status,c.description,c.thumbnail,c.start_date AS "startDate",c.end_date AS "endDate",c.survey_enabled AS "surveyEnabled",c.google_form_url AS "googleFormUrl",e.id AS "enrollmentId",e.required,e.status AS "enrollmentStatus",e.progress,e.completed_at AS "completedAt",EXISTS(SELECT 1 FROM reward_transactions rt WHERE rt.enrollment_id=e.id AND rt.activity_type='SURVEY_SUBMIT') AS "surveySubmitted" FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.user_id=$2 WHERE c.id=$1 AND c.deleted_at IS NULL`,[req.params.id,req.currentUser!.id]);if(!course.rowCount)return res.status(404).json({data:null,error:{code:"COURSE_NOT_FOUND"}});const lessons=await pool.query(`SELECT l.id,l.title,l.description,l.sequence,l.duration_minutes AS "durationMinutes",l.video_type AS "videoType",l.video_url AS "videoUrl",l.drive_file_id AS "driveFileId",l.attachment_name AS "attachmentName",l.attachment_drive_file_id AS "attachmentDriveFileId",l.goals,l.contents,l.completion_threshold AS "completionThreshold",lp.watched_percent AS "watchedPercent",COALESCE(lp.completed,false) completed FROM lessons l LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.enrollment_id=$2 WHERE l.course_id=$1 ORDER BY l.sequence`,[req.params.id,course.rows[0].enrollmentId||null]);for(const lesson of lessons.rows)lesson.quiz=(await pool.query(`SELECT q.id,q.question,q.options,q.explanation,EXISTS(SELECT 1 FROM quiz_attempts qa WHERE qa.question_id=q.id AND qa.enrollment_id=$2 AND qa.correct) AS "correctlyAnswered" FROM quiz_questions q WHERE q.lesson_id=$1 ORDER BY q.sequence`,[lesson.id,course.rows[0].enrollmentId||null])).rows;res.json({data:{...course.rows[0],lessons:lessons.rows},error:null});}catch(e){next(e);}});
 router.post("/courses/:id/enroll",async(req,res,next)=>{try{const open=await pool.query(`SELECT 1 FROM courses WHERE id=$1 AND status='OPEN' AND deleted_at IS NULL`,[req.params.id]);if(!open.rowCount)return res.status(409).json({data:null,error:{code:"COURSE_NOT_OPEN"}});const result=await pool.query(`INSERT INTO enrollments(course_id,user_id) VALUES($1,$2) ON CONFLICT(course_id,user_id) DO UPDATE SET status=CASE WHEN enrollments.status='CANCELLED' THEN 'ENROLLED' ELSE enrollments.status END,cancelled_at=NULL RETURNING *`,[req.params.id,req.currentUser!.id]);res.status(201).json({data:result.rows[0],error:null});}catch(e){next(e);}});
 router.delete("/enrollments/:id",async(req,res,next)=>{try{const result=await pool.query(`UPDATE enrollments SET status='CANCELLED',cancelled_at=now() WHERE id=$1 AND user_id=$2 AND required=false AND status<>'COMPLETED'`,[req.params.id,req.currentUser!.id]);if(!result.rowCount)return res.status(409).json({data:null,error:{code:"REQUIRED_OR_COMPLETED_CANNOT_CANCEL"}});res.status(204).end();}catch(e){next(e);}});
 router.put("/enrollments/:enrollmentId/lessons/:lessonId/progress",async(req,res,next)=>{const parsed=z.object({watchedPercent:z.number().int().min(0).max(100),manualComplete:z.boolean().optional().default(false)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR"}});try{const scope=await pool.query(`SELECT e.id,l.video_type,l.completion_threshold,l.title FROM enrollments e JOIN lessons l ON l.course_id=e.course_id WHERE e.id=$1 AND e.user_id=$2 AND l.id=$3 AND e.status<>'CANCELLED'`,[req.params.enrollmentId,req.currentUser!.id,req.params.lessonId]);if(!scope.rowCount)return res.status(404).json({data:null,error:{code:"ENROLLMENT_NOT_FOUND"}});const lesson=scope.rows[0],completed=lesson.video_type==='YOUTUBE'?parsed.data.manualComplete:parsed.data.watchedPercent>=lesson.completion_threshold;await pool.query(`INSERT INTO lesson_progress(enrollment_id,lesson_id,watched_percent,completed,completed_at) VALUES($1,$2,$3,$4,CASE WHEN $4 THEN now() END) ON CONFLICT(enrollment_id,lesson_id) DO UPDATE SET watched_percent=GREATEST(lesson_progress.watched_percent,EXCLUDED.watched_percent),completed=lesson_progress.completed OR EXCLUDED.completed,completed_at=CASE WHEN lesson_progress.completed OR EXCLUDED.completed THEN COALESCE(lesson_progress.completed_at,now()) END,updated_at=now()`,[req.params.enrollmentId,req.params.lessonId,parsed.data.watchedPercent,completed]);if(completed)await awardReward(pool,{userId:req.currentUser!.id,enrollmentId:req.params.enrollmentId,activityType:"LESSON_COMPLETE",sourceKey:`lesson:${req.params.enrollmentId}:${req.params.lessonId}`,description:`${lesson.title} 차시 완료`});res.json({data:await recalculate(pool,req.params.enrollmentId,config),error:null});}catch(e){next(e);}});
 router.post("/enrollments/:enrollmentId/quiz/:questionId",async(req,res,next)=>{const parsed=z.object({selectedOption:z.number().int().min(0).max(3)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR"}});try{const question=await pool.query(`SELECT q.correct_option,q.explanation,q.lesson_id AS "lessonId",l.title FROM quiz_questions q JOIN lessons l ON l.id=q.lesson_id JOIN enrollments e ON e.course_id=l.course_id WHERE q.id=$1 AND e.id=$2 AND e.user_id=$3`,[req.params.questionId,req.params.enrollmentId,req.currentUser!.id]);if(!question.rowCount)return res.status(404).json({data:null,error:{code:"QUESTION_NOT_FOUND"}});const correct=parsed.data.selectedOption===question.rows[0].correct_option;await pool.query(`INSERT INTO quiz_attempts(enrollment_id,question_id,selected_option,correct) VALUES($1,$2,$3,$4)`,[req.params.enrollmentId,req.params.questionId,parsed.data.selectedOption,correct]);const lessonId=question.rows[0].lessonId;const quiz=await pool.query(`SELECT COUNT(q.id)::int total,COUNT(DISTINCT qa.question_id) FILTER(WHERE qa.correct)::int correct FROM quiz_questions q LEFT JOIN quiz_attempts qa ON qa.question_id=q.id AND qa.enrollment_id=$2 WHERE q.lesson_id=$1`,[lessonId,req.params.enrollmentId]);if(quiz.rows[0]?.total>0&&quiz.rows[0].total===quiz.rows[0].correct)await awardReward(pool,{userId:req.currentUser!.id,enrollmentId:req.params.enrollmentId,activityType:"QUIZ_COMPLETE",sourceKey:`quiz:${req.params.enrollmentId}:${lessonId}`,description:`${question.rows[0].title} 퀴즈 완료`});const progress=await recalculate(pool,req.params.enrollmentId,config);res.json({data:{correct,correctOption:question.rows[0].correct_option,explanation:question.rows[0].explanation,...progress},error:null});}catch(e){next(e);}});
 router.post("/enrollments/:enrollmentId/survey",async(req,res,next)=>{try{const scope=await pool.query(`SELECT e.id,c.title FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.id=$1 AND e.user_id=$2 AND e.status<>'CANCELLED'`,[req.params.enrollmentId,req.currentUser!.id]);if(!scope.rowCount)return res.status(404).json({data:null,error:{code:"ENROLLMENT_NOT_FOUND"}});const reward=await awardReward(pool,{userId:req.currentUser!.id,enrollmentId:req.params.enrollmentId,activityType:"SURVEY_SUBMIT",sourceKey:`survey:${req.params.enrollmentId}`,description:`${scope.rows[0].title} 설문 제출`});const progress=await recalculate(pool,req.params.enrollmentId,config);res.json({data:{awarded:Boolean(reward),points:reward?.points||0,...progress},error:null});}catch(e){next(e);}});
 router.get("/certificates/:enrollmentId",async(req,res,next)=>{try{const result=await pool.query(`SELECT cert.certificate_number AS "certificateNumber",cert.issued_at AS "issuedAt",cert.drive_file_id AS "driveFileId",c.title,u.name,u.employee_number AS "employeeNumber" FROM certificates cert JOIN enrollments e ON e.id=cert.enrollment_id JOIN courses c ON c.id=e.course_id JOIN users u ON u.id=e.user_id WHERE e.id=$1 AND e.user_id=$2`,[req.params.enrollmentId,req.currentUser!.id]);if(!result.rowCount)return res.status(404).json({data:null,error:{code:"CERTIFICATE_NOT_FOUND"}});res.json({data:result.rows[0],error:null});}catch(e){next(e);}});return router;}
