import { Router } from "express";
import { z } from "zod";
import type { DatabasePool } from "../database/pool.js";
import { requireUser } from "../auth/middleware.js";
import type { AppConfig } from "../config.js";
import { uploadCertificate } from "../google/archive.js";

async function recalculate(pool:DatabasePool,enrollmentId:string,config?:AppConfig){
  const stats=await pool.query(`SELECT COUNT(l.id)::int total,COUNT(lp.id) FILTER(WHERE lp.completed)::int completed FROM enrollments e JOIN lessons l ON l.course_id=e.course_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.enrollment_id=e.id WHERE e.id=$1 GROUP BY e.id`,[enrollmentId]);
  const total=stats.rows[0]?.total||0,completed=stats.rows[0]?.completed||0,progress=total?Math.round(100*completed/total):0;
  const questions=await pool.query(`SELECT COUNT(q.id)::int total,COUNT(DISTINCT qa.question_id) FILTER(WHERE qa.correct)::int completed FROM enrollments e JOIN lessons l ON l.course_id=e.course_id LEFT JOIN quiz_questions q ON q.lesson_id=l.id LEFT JOIN quiz_attempts qa ON qa.question_id=q.id AND qa.enrollment_id=e.id WHERE e.id=$1 GROUP BY e.id`,[enrollmentId]);
  const quizDone=(questions.rows[0]?.total||0)===(questions.rows[0]?.completed||0),done=total>0&&progress===100&&quizDone;
  await pool.query(`UPDATE enrollments SET progress=$2,status=CASE WHEN $3 THEN 'COMPLETED' WHEN $2>0 THEN 'IN_PROGRESS' ELSE status END,completed_at=CASE WHEN $3 THEN COALESCE(completed_at,now()) ELSE completed_at END WHERE id=$1`,[enrollmentId,progress,done]);
  if(done){const certificateNumber=`SPARKPLUS-${new Date().getFullYear()}-${enrollmentId.slice(0,8).toUpperCase()}`;const inserted=await pool.query(`INSERT INTO certificates(enrollment_id,certificate_number) VALUES($1,$2) ON CONFLICT(enrollment_id) DO NOTHING RETURNING id`,[enrollmentId,certificateNumber]);if(inserted.rowCount&&config){const details=await pool.query(`SELECT u.name,u.email,c.title,cert.issued_at AS "issuedAt" FROM certificates cert JOIN enrollments e ON e.id=cert.enrollment_id JOIN users u ON u.id=e.user_id JOIN courses c ON c.id=e.course_id WHERE e.id=$1`,[enrollmentId]);uploadCertificate(config,{certificateNumber,...details.rows[0],issuedAt:new Date(details.rows[0].issuedAt).toISOString()}).then((driveFileId)=>driveFileId ? pool.query(`UPDATE certificates SET drive_file_id=$2 WHERE enrollment_id=$1`,[enrollmentId,driveFileId]) : null).catch(()=>undefined);}}return{progress,completed:done};
}
export function createLearningRouter(pool:DatabasePool,config?:AppConfig){const router=Router();router.use(requireUser(pool));
 router.get("/courses",async(req,res,next)=>{try{const result=await pool.query(`SELECT c.id,c.title,c.category,c.level,c.status,c.description,c.thumbnail,c.start_date AS "startDate",c.end_date AS "endDate",e.id AS "enrollmentId",e.required,e.due_date AS "dueDate",e.status AS "enrollmentStatus",e.progress,e.completed_at AS "completedAt",cert.certificate_number AS "certificateNumber" FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.user_id=$1 LEFT JOIN certificates cert ON cert.enrollment_id=e.id WHERE c.deleted_at IS NULL AND c.status='OPEN' ORDER BY e.required DESC NULLS LAST,c.created_at DESC`,[req.currentUser!.id]);res.json({data:result.rows,error:null});}catch(e){next(e);}});
 router.get("/courses/:id",async(req,res,next)=>{try{const course=await pool.query(`SELECT c.*,e.id AS "enrollmentId",e.required,e.status AS "enrollmentStatus",e.progress FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.user_id=$2 WHERE c.id=$1 AND c.deleted_at IS NULL`,[req.params.id,req.currentUser!.id]);if(!course.rowCount)return res.status(404).json({data:null,error:{code:"COURSE_NOT_FOUND"}});const lessons=await pool.query(`SELECT l.*,lp.watched_percent AS "watchedPercent",COALESCE(lp.completed,false) completed FROM lessons l LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.enrollment_id=$2 WHERE l.course_id=$1 ORDER BY l.sequence`,[req.params.id,course.rows[0].enrollmentId||null]);for(const lesson of lessons.rows)lesson.quiz=(await pool.query(`SELECT id,question,options,explanation FROM quiz_questions WHERE lesson_id=$1 ORDER BY sequence`,[lesson.id])).rows;res.json({data:{...course.rows[0],lessons:lessons.rows},error:null});}catch(e){next(e);}});
 router.post("/courses/:id/enroll",async(req,res,next)=>{try{const open=await pool.query(`SELECT 1 FROM courses WHERE id=$1 AND status='OPEN' AND deleted_at IS NULL`,[req.params.id]);if(!open.rowCount)return res.status(409).json({data:null,error:{code:"COURSE_NOT_OPEN"}});const result=await pool.query(`INSERT INTO enrollments(course_id,user_id) VALUES($1,$2) ON CONFLICT(course_id,user_id) DO UPDATE SET status=CASE WHEN enrollments.status='CANCELLED' THEN 'ENROLLED' ELSE enrollments.status END,cancelled_at=NULL RETURNING *`,[req.params.id,req.currentUser!.id]);res.status(201).json({data:result.rows[0],error:null});}catch(e){next(e);}});
 router.delete("/enrollments/:id",async(req,res,next)=>{try{const result=await pool.query(`UPDATE enrollments SET status='CANCELLED',cancelled_at=now() WHERE id=$1 AND user_id=$2 AND required=false AND status<>'COMPLETED'`,[req.params.id,req.currentUser!.id]);if(!result.rowCount)return res.status(409).json({data:null,error:{code:"REQUIRED_OR_COMPLETED_CANNOT_CANCEL"}});res.status(204).end();}catch(e){next(e);}});
 router.put("/enrollments/:enrollmentId/lessons/:lessonId/progress",async(req,res,next)=>{const parsed=z.object({watchedPercent:z.number().int().min(0).max(100),manualComplete:z.boolean().optional().default(false)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR"}});try{const scope=await pool.query(`SELECT e.id,l.video_type,l.completion_threshold FROM enrollments e JOIN lessons l ON l.course_id=e.course_id WHERE e.id=$1 AND e.user_id=$2 AND l.id=$3 AND e.status<>'CANCELLED'`,[req.params.enrollmentId,req.currentUser!.id,req.params.lessonId]);if(!scope.rowCount)return res.status(404).json({data:null,error:{code:"ENROLLMENT_NOT_FOUND"}});const lesson=scope.rows[0],completed=lesson.video_type==='YOUTUBE'?parsed.data.manualComplete:parsed.data.watchedPercent>=lesson.completion_threshold;await pool.query(`INSERT INTO lesson_progress(enrollment_id,lesson_id,watched_percent,completed,completed_at) VALUES($1,$2,$3,$4,CASE WHEN $4 THEN now() END) ON CONFLICT(enrollment_id,lesson_id) DO UPDATE SET watched_percent=GREATEST(lesson_progress.watched_percent,EXCLUDED.watched_percent),completed=lesson_progress.completed OR EXCLUDED.completed,completed_at=CASE WHEN lesson_progress.completed OR EXCLUDED.completed THEN COALESCE(lesson_progress.completed_at,now()) END,updated_at=now()`,[req.params.enrollmentId,req.params.lessonId,parsed.data.watchedPercent,completed]);res.json({data:await recalculate(pool,req.params.enrollmentId,config),error:null});}catch(e){next(e);}});
 router.post("/enrollments/:enrollmentId/quiz/:questionId",async(req,res,next)=>{const parsed=z.object({selectedOption:z.number().int().nonnegative()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({data:null,error:{code:"VALIDATION_ERROR"}});try{const question=await pool.query(`SELECT q.correct_option,q.explanation FROM quiz_questions q JOIN lessons l ON l.id=q.lesson_id JOIN enrollments e ON e.course_id=l.course_id WHERE q.id=$1 AND e.id=$2 AND e.user_id=$3`,[req.params.questionId,req.params.enrollmentId,req.currentUser!.id]);if(!question.rowCount)return res.status(404).json({data:null,error:{code:"QUESTION_NOT_FOUND"}});const correct=parsed.data.selectedOption===question.rows[0].correct_option;await pool.query(`INSERT INTO quiz_attempts(enrollment_id,question_id,selected_option,correct) VALUES($1,$2,$3,$4)`,[req.params.enrollmentId,req.params.questionId,parsed.data.selectedOption,correct]);const progress=await recalculate(pool,req.params.enrollmentId,config);res.json({data:{correct,correctOption:question.rows[0].correct_option,explanation:question.rows[0].explanation,...progress},error:null});}catch(e){next(e);}});
 router.get("/certificates/:enrollmentId",async(req,res,next)=>{try{const result=await pool.query(`SELECT cert.certificate_number AS "certificateNumber",cert.issued_at AS "issuedAt",cert.drive_file_id AS "driveFileId",c.title,u.name,u.employee_number AS "employeeNumber" FROM certificates cert JOIN enrollments e ON e.id=cert.enrollment_id JOIN courses c ON c.id=e.course_id JOIN users u ON u.id=e.user_id WHERE e.id=$1 AND e.user_id=$2`,[req.params.enrollmentId,req.currentUser!.id]);if(!result.rowCount)return res.status(404).json({data:null,error:{code:"CERTIFICATE_NOT_FOUND"}});res.json({data:result.rows[0],error:null});}catch(e){next(e);}});return router;}
